version: "3.9"

services:
  mysql-server:
    container_name: mysql-server
    hostname: mysql-server
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_DATABASE: 'esmc_db'
      # So you don't have to use root, but you can if you like
      #          MYSQL_USER: 'qsd'
      # You can use whatever password you like
      #          MYSQL_PASSWORD: 'sdfsdf'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3307'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - mysql-net
volumes:
  mysql-volume:
    name: mysql-server-volume
# Names our networks
networks:
  mysql-net:
    #      external:
    name: mysql-server-net